# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=24)),
                ('pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
